#!/usr/bin/env python3
"""Generate the compressed Unicode-to-CP936 table used by text_encoding.cc."""

import argparse
import base64
import struct
import textwrap
import zlib
from pathlib import Path


def build_table() -> bytes:
    values = []
    for code_point in range(0x10000):
        try:
            encoded = chr(code_point).encode("gbk")
        except UnicodeEncodeError:
            encoded = b""

        if len(encoded) == 1:
            value = encoded[0]
        elif len(encoded) == 2:
            value = (encoded[0] << 8) | encoded[1]
        else:
            value = 0

        values.append(value)

    return struct.pack("<65536H", *values)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    raw = build_table()
    compressed = zlib.compress(raw, 9)
    encoded = base64.b64encode(compressed).decode("ascii")

    lines = [
        "// Generated by tools/generate_gbk_mapping.py. Do not edit manually.",
        f"static constexpr unsigned long kUnicodeToGbkRawSize = {len(raw)};",
        f"static constexpr unsigned long kUnicodeToGbkCompressedSize = {len(compressed)};",
        f"static constexpr unsigned long kUnicodeToGbkCrc32 = 0x{zlib.crc32(raw):08X}UL;",
        "static constexpr char kUnicodeToGbkBase64[] =",
    ]
    for chunk in textwrap.wrap(encoded, 96):
        lines.append(f'    "{chunk}"')
    lines[-1] += ";"
    lines.append("")

    args.output.write_text("\n".join(lines), encoding="ascii")


if __name__ == "__main__":
    main()
